server:
  port: 8080

spring:
  profiles:
    active: dev  #???dev
  datasource:
      driver-class-name: ${billing.datasource.driver-class-name}
      url: jdbc:mysql://${billing.datasource.host}:${billing.datasource.port}/${billing.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: ${billing.datasource.username}
      password: ${billing.datasource.password}

mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gdxt.entity
  configuration:
    #??????
    map-underscore-to-camel-case: true

