billing:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: billing
    username: root
    password: root
  #当出现相同名字的类进行注册时，准许覆盖注册
spring:
  main:
    allow-bean-definition-overriding: true